Imports

In [1]:
import pandas as pd
import numpy as np

Load Data

In [2]:
fashion_df = pd.read_csv(
    '../data/processed/fashion_products.csv'
)

In [3]:
mens_df = pd.read_csv(
    '../data/processed/mens_fashion.csv'
)

Defining Categories

In [4]:
tops = [
    'Tshirts',
    'Shirts',
    'Kurtas',
    'Tops',
    'Sweatshirts',
    'Sweaters',
    'Jackets'
]

bottoms = [
    'Jeans',
    'Trousers',
    'Shorts',
    'Track Pants'
]

footwear = [
    'Casual Shoes',
    'Sports Shoes',
    'Formal Shoes'
]

In [5]:
tops_df = mens_df[
    mens_df['articleType'].isin(tops)
]

bottoms_df = mens_df[
    mens_df['articleType'].isin(bottoms)
]

footwear_df = mens_df[
    mens_df['articleType'].isin(footwear)
]

In [6]:
print("Tops:", len(tops_df))
print("Bottoms:", len(bottoms_df))
print("Footwear:", len(footwear_df))

Tops: 8775
Bottoms: 1363
Footwear: 4474

In [7]:
mens_df.shape

(14612, 10)

In [8]:
tops_df[['articleType','baseColour','usage','season']].sample(10)

       articleType baseColour   usage  season
12767      Tshirts     Purple  Casual  Summer
11109       Kurtas      Black  Ethnic  Summer
4508       Tshirts        Red  Casual  Summer
1409        Shirts       Blue  Formal  Summer
11039       Shirts      Green  Casual  Summer
11158     Sweaters       Grey  Casual    Fall
7994      Sweaters      Green  Casual    Fall
546    Sweatshirts       Grey  Casual    Fall
10386      Tshirts      White  Casual  Summer
1037       Jackets      White  Casual    Fall

In [9]:
bottoms_df[['articleType','baseColour','usage','season']].sample(10)

       articleType baseColour   usage  season
11518       Shorts       Grey  Sports  Summer
12665     Trousers      Khaki  Casual    Fall
614       Trousers      Black  Casual  Summer
3754         Jeans       Blue  Casual    Fall
12377       Shorts        Red  Casual  Summer
8824         Jeans       Blue  Casual  Summer
14095        Jeans       Blue  Casual  Summer
14004       Shorts  Navy Blue  Casual  Spring
10654  Track Pants  Navy Blue  Sports  Summer
4763   Track Pants      Black  Sports    Fall

In [21]:
footwear_df[['articleType','baseColour','usage','season']].sample(10)

        articleType baseColour   usage  season
3995   Sports Shoes       Grey  Sports  Summer
9374   Sports Shoes      White  Sports  Spring
297    Casual Shoes      Brown  Casual    Fall
3695   Sports Shoes      Black  Sports  Summer
14057  Sports Shoes       Grey  Sports    Fall
13179  Formal Shoes      Brown  Formal    Fall
14324  Casual Shoes      Black  Casual  Summer
11127  Sports Shoes      White  Sports  Summer
5980   Sports Shoes      White  Sports    Fall
12848  Casual Shoes      Brown  Casual    Fall

Sample Data

In [10]:
tops_sample = tops_df.sample(100, random_state=42)
bottoms_sample = bottoms_df.sample(100, random_state=42)
footwear_sample = footwear_df.sample(100, random_state=42)

In [11]:
import random

Outfit Combinations

In [12]:
outfits = []

for _ in range(3000):
    
    top = tops_sample.sample(1).iloc[0]
    bottom = bottoms_sample.sample(1).iloc[0]
    shoe = footwear_sample.sample(1).iloc[0]

    outfits.append({
        'top_type': top['articleType'],
        'top_color': top['baseColour'],
        'top_usage': top['usage'],
        'top_season': top['season'],

        'bottom_type': bottom['articleType'],
        'bottom_color': bottom['baseColour'],
        'bottom_usage': bottom['usage'],
        'bottom_season': bottom['season'],

        'shoe_type': shoe['articleType'],
        'shoe_color': shoe['baseColour'],
        'shoe_usage': shoe['usage'],
        'shoe_season': shoe['season']
    })

outfits_df = pd.DataFrame(outfits)

In [13]:
outfits_df.head()

,top_type,top_color,top_usage,top_season,bottom_type,bottom_color,bottom_usage,bottom_season,shoe_type,shoe_color,shoe_usage,shoe_season
0,Tshirts,Grey,Sports,Summer,Shorts,Blue,Casual,Summer,Casual Shoes,White,Casual,Fall
1,Tshirts,Blue,Casual,Fall,Jeans,Blue,Casual,Summer,Sports Shoes,Blue,Sports,Summer
2,Tshirts,Green,Sports,Fall,Jeans,Blue,Casual,Summer,Sports Shoes,Black,Sports,Summer
3,Tshirts,Black,Sports,Fall,Track Pants,Navy Blue,Sports,Summer,Casual Shoes,Blue,Casual,Fall
4,Tshirts,Green,Sports,Fall,Track Pants,Black,Sports,Fall,Casual Shoes,Blue,Casual,Fall

In [14]:
outfits_df.shape

(3000, 12)

In [15]:
print(tops_sample.shape)
print(bottoms_sample.shape)
print(footwear_sample.shape)

(100, 10)
(100, 10)
(100, 10)

In [16]:
outfits_df.head()
outfits_df.shape

(3000, 12)

In [17]:
outfits_df.to_csv(
    '../data/processed/outfit_combinations.csv',
    index=False
)